//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hethongquanlixe.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int IdAcc { get; set; }
        public string Tendangnhap { get; set; }
        public string MatKhau { get; set; }
        public string Email { get; set; }
        public string Vaitro { get; set; }
        public string HoTen { get; set; }
        public string SoDienThoai { get; set; }
        public string DiaChi { get; set; }
        public string GhiChu { get; set; }
    }
}
