//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hethongquanlixe.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDong
    {
        public int Idhopdong { get; set; }
        public Nullable<int> Manhanvien { get; set; }
        public Nullable<int> Makhachhang { get; set; }
        public string Loaihopdong { get; set; }
        public Nullable<System.DateTime> Ngaydi { get; set; }
        public Nullable<System.DateTime> Ngayve { get; set; }
        public Nullable<double> Datcoc { get; set; }
        public Nullable<double> Giathue { get; set; }
        public Nullable<double> Phuthu { get; set; }
        public Nullable<System.DateTime> Ngaytao { get; set; }
        public Nullable<System.DateTime> Ngaysua { get; set; }
        public Nullable<int> Madichvu { get; set; }
        public string Nguoitaohd { get; set; }
        public Nullable<int> Mayeucau { get; set; }
        public Nullable<int> Matinhtrang { get; set; }
        public string Ghichu { get; set; }
    }
}
