//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hethongquanlixe.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public int Id { get; set; }
        public string Tenkhachhang { get; set; }
        public Nullable<int> Sodienthoai { get; set; }
        public string Email { get; set; }
        public string Diachi { get; set; }
        public Nullable<int> Manhomkh { get; set; }
        public string Ghichu { get; set; }
    }
}
