//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hethongquanlixe.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HethongquanlithuexeEntities : DbContext
    {
        public HethongquanlithuexeEntities()
            : base("name=HethongquanlithuexeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<DichVu> DichVus { get; set; }
        public virtual DbSet<HopDong> HopDongs { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<LoaiXe> LoaiXes { get; set; }
        public virtual DbSet<NhomKhachHang> NhomKhachHangs { get; set; }
        public virtual DbSet<TaiXe> TaiXes { get; set; }
        public virtual DbSet<TinhTrangTaiXe> TinhTrangTaiXes { get; set; }
        public virtual DbSet<TrangThaiYeuCau> TrangThaiYeuCaus { get; set; }
        public virtual DbSet<Xe> Xes { get; set; }
        public virtual DbSet<YeuCau> YeuCaus { get; set; }
    }
}
