//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hethongquanlixe.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiXe
    {
        public int IdTaiXe { get; set; }
        public string HotenTaiXe { get; set; }
        public Nullable<int> SoDienThoai { get; set; }
        public string Email { get; set; }
        public string DiaChi { get; set; }
        public string LoaiBanglai { get; set; }
        public Nullable<int> Matinhtrangxe { get; set; }
        public string GhiChu { get; set; }
    }
}
