//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hethongquanlixe.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xe
    {
        public int IdXe { get; set; }
        public string Tenxe { get; set; }
        public string Hangxe { get; set; }
        public string Mauxe { get; set; }
        public string Bienkiemsoat { get; set; }
        public string Maloaixe { get; set; }
        public Nullable<int> Matinhtrangxe { get; set; }
        public string Ghichu { get; set; }
    }
}
