//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hethongquanlixe.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class YeuCau
    {
        public int IdYC { get; set; }
        public Nullable<int> Makhachhang { get; set; }
        public Nullable<int> Mahopdong { get; set; }
        public Nullable<System.DateTime> NgayDi { get; set; }
        public Nullable<System.DateTime> NgayVe { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> Ngaysua { get; set; }
        public Nullable<int> Madichvu { get; set; }
        public Nullable<int> Manhanvien { get; set; }
        public Nullable<int> Mayeucau { get; set; }
        public Nullable<int> Matrangthai { get; set; }
        public Nullable<int> Maxe { get; set; }
        public string Ghichu { get; set; }
    }
}
